# Generated by Django 3.2 on 2021-06-23 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cover_photos', models.ImageField(blank=True, null=True, upload_to='cover_photos')),
                ('cover_photos_2', models.ImageField(blank=True, null=True, upload_to='cover_photos')),
                ('cover_photos_3', models.ImageField(blank=True, null=True, upload_to='cover_photos')),
                ('condition', models.CharField(choices=[('new', 'new'), ('old', 'old')], max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('num_of_days', models.IntegerField(default=0)),
                ('amount_paid', models.IntegerField(default=0)),
                ('days', models.CharField(choices=[(3, 3), (7, 7), (10, 10)], max_length=20)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('brand_name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
