# Generated by Django 3.2 on 2021-06-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='delete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
