# Generated by Django 3.2 on 2021-06-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_advert_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='days',
            field=models.CharField(choices=[(3, 3), (7, 7), (10, 10)], max_length=20),
        ),
    ]
