# Generated by Django 3.2 on 2021-06-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='clicks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
