# Generated by Django 3.2 on 2021-07-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_advert_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='ref_code',
            field=models.CharField(blank=True, default='9196666987795', max_length=50, null=True),
        ),
    ]
