# Generated by Django 3.2 on 2021-07-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_advert_ref_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='withdraw',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='withdraw',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='ref_code',
            field=models.CharField(blank=True, default='4922409637430', max_length=50, null=True),
        ),
    ]
