# Generated by Django 3.2 on 2021-06-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ip_address',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
