# Generated by Django 3.2 on 2021-06-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='package',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
