# Generated by Django 3.2 on 2021-06-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='package',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
    ]
