# Generated by Django 3.2 on 2021-06-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='clicks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
