# Generated by Django 3.2 on 2021-06-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ref_code',
            field=models.CharField(blank=True, default='6261170490388', max_length=50, null=True),
        ),
    ]
