# Generated by Django 3.2 on 2021-07-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_ref_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ref_code',
            field=models.CharField(blank=True, default='4041749790111', max_length=50, null=True),
        ),
    ]
